# Base docker-compose.yml
# Depend on ```source YOUR_ENV_FILE```
version: "3.8"

services:
  backend:
    build:
      context: .
    image: siema-tech-backend-service
    container_name: siema-tech-backend-service
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - siema-tech-network

  # In order to use .env vars in health script below
  # you have to run ```source YOUR_ENV_FILE```
  db:
    image: postgres:alpine
    container_name: siema-tech-db
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    

networks:
  siema-tech-network:
    name: siema-tech-network
    driver: bridge
