version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: siema-tech-backend-service
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production

  db:
    image: postgres:alpine
    container_name: siema-tech-db
    env_file:
      - .env.production.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
